
[build]
  command = """
    rustup install nightly --profile minimal \
      && cargo doc \
        --workspace \
        --no-deps \
        --all-features \
        --document-private-items
    """
  publish = "target/doc"

[build.environment]
  RUSTDOCFLAGS="--cfg docsrs"

[[redirects]]
  from = "/"
  to = "/mycelium_kernel"