pre-release-commit-message = "chore: release {{crate_name}} v{{version}}"
tag-message = "{{tag_name}}"
tag-name = "{{crate_name}}-v{{version}}"
pre-release-hook = [
    "git-cliff",
    "--workdir",
    "..",
    "--include-path",
    "{{crate_name}}",
    "--prepend",
    "{{crate_name}}/CHANGELOG.md",
    "--latest",
    "--tag",
    "{{crate_name}}-v{{version}}",
]