[target.'cfg(all(target_arch = "x86_64", target_os="none"))']
runner = "cargo run --release --package inoculate -- inoculate"

[alias]
xtask = "run --release --package inoculate -- xtask"
run-x64 = "run -Z build-std=core,alloc --target=x86_64-mycelium.json -- run"
debug-x64 = "run -Z build-std=core,alloc --target=x86_64-mycelium.json -- run --serial --gdb"
test-x64 = "test -Z build-std=core,alloc --target=x86_64-mycelium.json -- test"
clippy-x64 = "clippy -Z build-std=core,alloc --target=x86_64-mycelium.json"
build-x64 = "run -Z build-std=core,alloc --target=x86_64-mycelium.json --"
inoculate = "run -Z build-std=core,alloc --target=x86_64-mycelium.json --"
